// <auto-generated>
// This file is generated by scripts/Generate-ToolDescriptions.ps1
// Do not edit manually - changes will be overwritten.
// Regenerate with: pwsh scripts/Generate-ToolDescriptions.ps1
// </auto-generated>

namespace PowerShellMcpServer.pwsh_repl.Tools;

public static class ToolDescriptions
{
    public const string PwshToolDescription = @"Execute PowerShell with persistent sessions. Variables and state persist across calls within the same sessionId.

**Modules auto-loaded:** Base, AgentBlocks, TokenCounter + PWSH_MCP_MODULES (e.g., LoraxMod, SessionLog)
**Check loaded modules:** Use pwsh_mcp://modules resource

**Mode callback pattern:** Use mode parameter to call module functions directly:
  mode='Invoke-DevRun' + script='dotnet build' + kwargs={Streams: ['Error']}

**Auto-caching:** All executions cached in $global:DevRunCache with auto-generated names (pwsh_1, pwsh_2, ...)

**Python scripts:** Use here-string + pipe to avoid escaping issues:
  $code = @'
  print(f""Any 'quotes' and {braces} work"")
  '@
  $code | python -
## Quick Reference

**AgentBlocks** - Pattern learning (43 pre-configured patterns)
  Get-Patterns [-Name] [-Category]
  Set-Pattern -Name -Pattern -Description [-Category]
  Test-Pattern -Name [-Sample] [-ShowMatches]
  (+38 more: Get-Command -Module AgentBlocks)

**TokenCounter** - Claude token counting (tiktoken)
  Measure-Tokens [-Text] [-Model] [-CondaEnvironment]

**SessionLog** - Session tracking (JSONL, 4AM boundary)
  Add-Todo -Text | Update-TodoStatus -Index -Status
  Show-Session [-Last] | Read-SessionLog [-Last]
  (External module via PWSH_MCP_MODULES)

**LoraxMod** - Tree-sitter AST parsing v1.0.1 (28 languages, experimental)
  # Parse code to AST
  ConvertTo-LoraxAST -Code $code -Language python [-Recurse]
  # Semantic diff (structure-aware, not text)
  Compare-LoraxAST -OldCode $old -NewCode $new -Language csharp
  # Dead code pattern: find defined vs called
  $funcs = Find-LoraxFunction -Language python -FilePath $file
  $calls = Find-LoraxNode -Language python -FilePath $file -NodeTypes @('call')
  (External module via PWSH_MCP_MODULES)

Use Get-Help <function> -Full for detailed documentation.
";
}
